# Generated by Django 6.0.3 on 2026-04-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(default=True, verbose_name="Доступен"),
        ),
    ]
